# Site settings
title: OpenStreetMap Colombia
intro: "Brinda ayuda a las comunidades e indígenas Wayuu, inscríbete!"
header-img: img/watercolor_guajira.png
email: your-email@yourdomain.com
description: "Bienvenidos al sitio de la OSM Colombia, creando mapas para emergencias."
baseurl: ""
url: "http://OpenStreetMap.CO"
twitter_username: OpenStreetMapCO
github_username:  OpenStreetMapColombia
facebook_username:  OpenStreetMapColombia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
