title: OpenStreetMap Colombia
description: Para la cartografía libre del país

url: http://openstreetmapcolombia.github.co/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Inicio
   url: /index.html
 - title: Acerca
   url: /acerca
 - title: Contacto
   url: /contacto

social:
   github: openstreetmapcolombia
   twitter: OpenStreetMapCo
   facebook: OpenStreetMapCo
   email: info@openstreetmap.co

google_analytics: "XX-UA-58263416-1"

timezone: America/Bogota
