# Site settings
title: Comunidad OpenStreetMap Colombia
intro: Noticias sobre las actividades de la comunidad OSM colombia
header-img: img/guapi.jpg
email: info@openstreetmap.co
description: "Bienvenidos al blog de la Comunidad OSM Colombia"
# button: '<br><br><a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>'
twitter_username: OpenStreetMapCO
github_username:  OpenStreetMapColombia
facebook_username:  groups/98009745459
telegram_username: osmco

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: ['jekyll-paginate']
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "Gemfile", "Gemfile.lock"]

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
#analytics :
#  provider : google
#  google :
#      tracking_id : 'UA-71933255-1'

timezone: America/Bogota
