# Site settings
title: OpenStreetMap Colombia
intro: Riohacha y Maicao
header-img: galeria/30-dscf5279_mapatonxguajira_rancheria_25474477765_o.jpg
email: info@openstreetmap.co
description: "Bienvenidos al sitio de la OSM Colombia, creando mapas para emergencias."
# button: '<br><br><a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>'
baseurl: ""
url: "http://blog.openstreetmap.co"
twitter_username: OpenStreetMapCO
github_username:  OpenStreetMapColombia
facebook_username:  groups/98009745459

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: ['jekyll-paginate']
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md", "Gemfile", "Gemfile.lock"]

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics :
  provider : google
  google :
      tracking_id : 'UA-71933255-1'

